### ISSUE TITLE
Keyboard shortcut/s which include Display Destination?

### ISSUE THREAD

**Issue by ipanema99** [peterdotjs/tab-resize#78] opened 2019-01-29 23:12 UTC
Is there a way to add a keyboard shortcut to select a display/monitor, or ideally to select both the destination display AND  1x1 layout? My goal is to easily toggle my gmail window back and forth between my laptop monitor, using keyboard shortcut(s). 

Currently these steps seem to be required:
1. Activate Tab Resize (via keyboard shortcut)
2. CLICK destination display (is a keyboard shortcut available?)
3. CLICK desired layout (layout shortcuts don't currently work if you change destination display)

Is there a simpler way?

Thanks!

**Comment by peterdotjs** [comment] 2021-04-09 00:02
Duplicate of https://github.com/peterdotjs/tab-resize/issues/49

**Closed by peterdotjs** 2021-04-09 00:02 UTC
Labels: duplicate, enhancement
