### ISSUE TITLE
Feature Request: Gather all tabs into single window

### ISSUE THREAD

**Issue by TheIronMarx** [peterdotjs/tab-resize#80] opened 2019-10-26 18:09 UTC
If I have tabs tiled, but I need to add more, it's tedious to bring them all together and change up the tab split. If there was a command to put all commands into a single window to then split out how ever I wanted to again, it would be very handy.

**Comment by peterdotjs** [comment] 2021-04-08 23:21
There is an existing extension that already does this - Tab Glue but also wouldn't be hard to add this. Something to consider for future iterations. Thanks for the feedback.

**Comment by peterdotjs** [comment] 2021-04-08 23:33
Duplicate of https://github.com/peterdotjs/tab-resize/issues/69

**Closed by peterdotjs** 2021-04-08 23:33 UTC
Labels: duplicate, enhancement
