### ISSUE TITLE
Enhancement - Custom window size and location

### ISSUE THREAD

**Issue by soundslikeodd** [peterdotjs/tab-resize#53] opened 2016-11-10 19:02 UTC
It would be cool if a user can define a window size and location as an option.  The settings could be height and width in px and x y location.

I am interested in attempting to add this enhancement and submitting it as a pull request.  Are PRs accepted openly?

**Comment by peterdotjs** [comment] 2016-11-10 19:22
PRs are definitely accepted! I really haven't updated the extension in some time but if you're interested by all means. It definitely sounds like more of an advanced feature that only a subset of users could take advantage of though. 

In the past I've had in mind a generic UI where windows could be added, dragged and dropped and resized. 

The challenges I think are adding such a feature but supporting multiple screens, and multiple layouts, while still providing a good user experience. But if you have ideas and interest I would definitely be open to discussion.

**Comment by soundslikeodd** [comment] 2017-01-05 04:14
PR is the direction I will head.  It might take me some time.  I have very little javascript experience.

Thank you for your input.

**Comment by peterdotjs** [comment] 2017-01-06 18:17
@soundslikeodd take all the time you need :) I haven't made meaningful updates since 2015 but let me know if you have any questions with existing code.

**Comment by laced66** [comment] 2017-01-31 02:36
What I need is 2 tabs on the right, and one on the left. Or 2 tabs on the left, and one on the right. I've downloaded WinSplit Revolution 11.04, because Tab Resize hasn't got this option. Please add it into the shortcuts and buttons.

**Comment by peterdotjs** [comment] 2017-12-20 18:01
Essentially duplicate of https://github.com/peterdotjs/tab-resize/issues/45

**Closed by peterdotjs** 2017-12-20 18:01 UTC
Labels: duplicate
