### ISSUE TITLE
do the grids have to be grids with x rows and y cols?

### ISSUE THREAD

**Issue by sasgrw** [peterdotjs/tab-resize#68] opened 2018-03-13 21:22 UTC
is it possible to split one grid cell into multiple cells?  so i could create a grid that has 2 rows, with the top row going from left to right, but the bottom row being split into two columns?

![image](https://user-images.githubusercontent.com/9466851/37370577-44f50984-26d2-11e8-9de3-b1b2dcf564c3.png)

**Comment by peterdotjs** [comment] 2021-04-08 23:35
Definitely possible to implement but would require some thinking about how to still create a simplistic UI. Possible enhancement for 3.0

Duplicate of https://github.com/peterdotjs/tab-resize/issues/84

**Closed by peterdotjs** 2021-04-08 23:35 UTC
Labels: duplicate, enhancement
