### ISSUE TITLE
Option to restore all tabs to 1x1

### ISSUE THREAD

**Issue by nickkjordan** [peterdotjs/tab-resize#48] opened 2016-04-21 02:23 UTC
I'm looking for a way to restore all my open tabs on one monitor to a single window, i.e. after a 1x2 split to  1x1.

Thanks for the project!

**Comment by peterdotjs** [comment] 2016-04-21 17:11
@nickkjordan the extension has an Undo button that reverts the last resize change. If you simply want to move all tabs/windows into a single window regardless of resizing actions you can install Tab glue. https://chrome.google.com/webstore/detail/tab-glue/mfedioikeigljhjfpghdejnogniddhna?hl=en

**Comment by digeomel** [comment] 2016-07-08 10:00
Why should we have to add another extension for this? To me it's obvious that once you have split your tabs and finished what you were doing, you should be able to go back to the "merged" state.
Please add an option for this in your extension :wink:

**Comment by peterdotjs** [comment] 2016-07-08 16:51
@digeomel the issue is going back to a merged state is a really one off feature not connected to the extension features. I want to avoid making the extension a kitchen sink of features related moving tabs around. Tab glue itself blindly moves all tabs into one window. In my mind a perfect tab glue like extension would display all the windows/tabs available and let the user decide where to move things around. If there is any action on the extension I'd like for it to be predictable rather than unpredictable. The user should know exactly which tabs are moving where.

**Closed by peterdotjs** 2016-07-08 16:51 UTC
